p8105_hw3_ei2262
================

# Problem 0

# Problem 1

``` r
library(p8105.datasets)
data("instacart")
```

### How many aisles are there, and which aisles are the most ordered from?

There are 134 aisles. The aisles that were ordered from the most are

### Plot: Displaying the number of items ordered in each aisle

``` r
instacart %>% 
  group_by(aisle, add_to_cart_order) %>% 
  mutate(
    orders = aisles > 10000
  ) 
```

### Table: Three post popular items in “Baking Ingredients”, “Dog Food Care”, and “Packaged Vegetable Fruits” aisles

``` r
instacart %>% 
  group_by(aisle, add_to_cart_order) %>% 
  instacart[which(instacart$aisles == "baking ingredients", "dog food care", "packaged vegetable fruits")]
```

# Problem 2

##### Load, tidy, and wrangle `accel_data.csv`

``` r
accel = read_csv("accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    week_day = case_when(
      day == 'Saturday' | day == 'Sunday' ~ 'weekend',
      day != 'Saturday' | day != 'Sunday' ~ 'weekday'
    )) %>% 
  select(week, day_id, day, week_day, everything()) %>% 
  mutate(
    day = as.factor(day)
  )
```

    ## Rows: 35 Columns: 1443
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr    (1): day
    ## dbl (1442): week, day_id, activity.1, activity.2, activity.3, activity.4, ac...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
print(accel)
```

    ## # A tibble: 35 × 1,444
    ##     week day_id day      week_…¹ activ…² activ…³ activ…⁴ activ…⁵ activ…⁶ activ…⁷
    ##    <dbl>  <dbl> <fct>    <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1     1      1 Friday   weekday    88.4    82.2    64.4    70.0    75.0    66.3
    ##  2     1      2 Monday   weekday     1       1       1       1       1       1  
    ##  3     1      3 Saturday weekend     1       1       1       1       1       1  
    ##  4     1      4 Sunday   weekend     1       1       1       1       1       1  
    ##  5     1      5 Thursday weekday    47.4    48.8    46.9    35.8    49.0    44.8
    ##  6     1      6 Tuesday  weekday    64.8    59.5    73.7    45.7    42.4    58.4
    ##  7     1      7 Wednesd… weekday    71.1   103.     68.5    45.4    37.8    18.3
    ##  8     2      8 Friday   weekday   675     542    1010     779     509     106  
    ##  9     2      9 Monday   weekday   291     335     393     335     263     675  
    ## 10     2     10 Saturday weekend    64      11       1       1       1       1  
    ## # … with 25 more rows, 1,434 more variables: activity_7 <dbl>,
    ## #   activity_8 <dbl>, activity_9 <dbl>, activity_10 <dbl>, activity_11 <dbl>,
    ## #   activity_12 <dbl>, activity_13 <dbl>, activity_14 <dbl>, activity_15 <dbl>,
    ## #   activity_16 <dbl>, activity_17 <dbl>, activity_18 <dbl>, activity_19 <dbl>,
    ## #   activity_20 <dbl>, activity_21 <dbl>, activity_22 <dbl>, activity_23 <dbl>,
    ## #   activity_24 <dbl>, activity_25 <dbl>, activity_26 <dbl>, activity_27 <dbl>,
    ## #   activity_28 <dbl>, activity_29 <dbl>, activity_30 <dbl>, …

In the `accel` dataset, there are 35 rows and 1444 columns. 1400 columns
represent 5 weeks worth of accelerometer data collected on a 63-year-old
male with a BMI 25. There are 4 columns that represent each `week`,
starting from week 1 to week 5, each day of the week data was collected,
which is represented by `day_id` and `day`, and whether the day was a
weekday or weekend.

###### Total Activity Over the Day

``` r
accel$total_activity = rowSums(accel[,c(5:1444)])

accel[c("week","day","total_activity")] %>% 
  kable()
```

| week | day       | total_activity |
|-----:|:----------|---------------:|
|    1 | Friday    |      480542.62 |
|    1 | Monday    |       78828.07 |
|    1 | Saturday  |      376254.00 |
|    1 | Sunday    |      631105.00 |
|    1 | Thursday  |      355923.64 |
|    1 | Tuesday   |      307094.24 |
|    1 | Wednesday |      340115.01 |
|    2 | Friday    |      568839.00 |
|    2 | Monday    |      295431.00 |
|    2 | Saturday  |      607175.00 |
|    2 | Sunday    |      422018.00 |
|    2 | Thursday  |      474048.00 |
|    2 | Tuesday   |      423245.00 |
|    2 | Wednesday |      440962.00 |
|    3 | Friday    |      467420.00 |
|    3 | Monday    |      685910.00 |
|    3 | Saturday  |      382928.00 |
|    3 | Sunday    |      467052.00 |
|    3 | Thursday  |      371230.00 |
|    3 | Tuesday   |      381507.00 |
|    3 | Wednesday |      468869.00 |
|    4 | Friday    |      154049.00 |
|    4 | Monday    |      409450.00 |
|    4 | Saturday  |        1440.00 |
|    4 | Sunday    |      260617.00 |
|    4 | Thursday  |      340291.00 |
|    4 | Tuesday   |      319568.00 |
|    4 | Wednesday |      434460.00 |
|    5 | Friday    |      620860.00 |
|    5 | Monday    |      389080.00 |
|    5 | Saturday  |        1440.00 |
|    5 | Sunday    |      138421.00 |
|    5 | Thursday  |      549658.00 |
|    5 | Tuesday   |      367824.00 |
|    5 | Wednesday |      445366.00 |

I created a table that shows the `total_activity` for each day for each
week data was collected.

Looking at the table created, there is no apparent trends across the 5
weeks.

###### Plotting 24-hour activity

``` r
accel %>% 
  ggplot(aes(x = total_activity, color = day)) +
  geom_histogram()
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

![](p8105_hw3_ei2262_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

# Problem 3

``` r
library(p8105.datasets)
data("ny_noaa")


print(ny_noaa)
```

    ## # A tibble: 2,595,176 × 7
    ##    id          date        prcp  snow  snwd tmax  tmin 
    ##    <chr>       <date>     <int> <int> <int> <chr> <chr>
    ##  1 US1NYAB0001 2007-11-01    NA    NA    NA <NA>  <NA> 
    ##  2 US1NYAB0001 2007-11-02    NA    NA    NA <NA>  <NA> 
    ##  3 US1NYAB0001 2007-11-03    NA    NA    NA <NA>  <NA> 
    ##  4 US1NYAB0001 2007-11-04    NA    NA    NA <NA>  <NA> 
    ##  5 US1NYAB0001 2007-11-05    NA    NA    NA <NA>  <NA> 
    ##  6 US1NYAB0001 2007-11-06    NA    NA    NA <NA>  <NA> 
    ##  7 US1NYAB0001 2007-11-07    NA    NA    NA <NA>  <NA> 
    ##  8 US1NYAB0001 2007-11-08    NA    NA    NA <NA>  <NA> 
    ##  9 US1NYAB0001 2007-11-09    NA    NA    NA <NA>  <NA> 
    ## 10 US1NYAB0001 2007-11-10    NA    NA    NA <NA>  <NA> 
    ## # … with 2,595,166 more rows

### *Description*

The `ny_noaa` dataset has 2,595,176 rows and 7 columns. A large majority
of observations for the variables `prcp`, `snow`, `snwd`, `tmax`, and
`tmin`. Due to this large number of *N/A* observations, it is difficult
to obtain interpretable data from the dataset. The `id` variable
represents the different weather station IDs. However, the way `id` is
currently makes it difficult to know which weather station each
observation is related to.

###### Data Cleaning

``` r
library(lubridate)
```

    ## 
    ## Attaching package: 'lubridate'

    ## The following objects are masked from 'package:base':
    ## 
    ##     date, intersect, setdiff, union

``` r
ny_noaa %>%
  mutate(date = as.Date(date, format = "%m-%d-%y")) %>%
  separate(date,c('year', 'month', 'date'),'-') %>% 
  mutate(
    prcp = 10 * prcp
  )
```

    ## # A tibble: 2,595,176 × 9
    ##    id          year  month date   prcp  snow  snwd tmax  tmin 
    ##    <chr>       <chr> <chr> <chr> <dbl> <int> <int> <chr> <chr>
    ##  1 US1NYAB0001 2007  11    01       NA    NA    NA <NA>  <NA> 
    ##  2 US1NYAB0001 2007  11    02       NA    NA    NA <NA>  <NA> 
    ##  3 US1NYAB0001 2007  11    03       NA    NA    NA <NA>  <NA> 
    ##  4 US1NYAB0001 2007  11    04       NA    NA    NA <NA>  <NA> 
    ##  5 US1NYAB0001 2007  11    05       NA    NA    NA <NA>  <NA> 
    ##  6 US1NYAB0001 2007  11    06       NA    NA    NA <NA>  <NA> 
    ##  7 US1NYAB0001 2007  11    07       NA    NA    NA <NA>  <NA> 
    ##  8 US1NYAB0001 2007  11    08       NA    NA    NA <NA>  <NA> 
    ##  9 US1NYAB0001 2007  11    09       NA    NA    NA <NA>  <NA> 
    ## 10 US1NYAB0001 2007  11    10       NA    NA    NA <NA>  <NA> 
    ## # … with 2,595,166 more rows
